/**
 * OpenAI API client for Earth Agent
 * 
 * Handles communication with OpenAI's GPT API using the official SDK
 */

import OpenAI from 'openai';
import { getApiKey } from '../config';

/**
 * Call the OpenAI API with a prompt
 * @param prompt User message
 * @param systemMessage System instructions
 * @param model OpenAI model to use (default: gpt-4-turbo-preview)
 * @returns The model's response text
 */
export const callOpenAIAPI = async (
  prompt: string, 
  systemMessage: string,
  model: string = 'gpt-4-1106-preview'
): Promise<string> => {
  try {
    // Get API key
    const apiKey = await getApiKey();
    if (!apiKey) {
      throw new Error('No API key configured. Please set your API key in the settings.');
    }

    // Initialize the OpenAI client
    const openai = new OpenAI({
      apiKey: apiKey,
      dangerouslyAllowBrowser: true // Required for browser usage
    });
    
    // Make the API call
    const response = await openai.chat.completions.create({
      model: model,
      messages: [
        { role: 'system', content: systemMessage },
        { role: 'user', content: prompt }
      ],
      temperature: 0,
      max_tokens: 2048
    });
    
    // Return the response text
    return response.choices[0]?.message?.content || 'No response generated by the model.';
  } catch (error) {
    console.error('Error calling OpenAI API:', error);
    throw error;
  }
}; 